server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_managment
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect