server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_managment
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
  jwt:
    secret-key: "MWIxNzc4NDg0MjMzNDVmZGY4ZjgwZTBkMDU4ZWVjYWNiMTdkZjMwNTJhOTNmNDZiYWVmN2MyOGQyNjQ2MzdiMTc="
    expiration-time: 2628000000
    refresh-expiration-time: 864000000
  oauth2:
    client:
      registration:
        google:
          client-id: 114690352756-e4arg6bpv6fec149g6mfufm8rctihl3p.apps.googleusercontent.com
          client-secret: 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
          scope: profile, email
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      provider:
        google:
          authorization-uri: https://accounts.google.com/o/oauth2/auth
          token-uri: https://oauth2.googleapis.com/token
          user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo